# Generated by Django 5.2.8 on 2025-12-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name="Ім'я користувача")),
                ('first_name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Електронна пошта')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата приєднання')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
        ),
    ]
